# Generated by Django 3.1.2 on 2020-11-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Anonymous', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='primary_genre',
            field=models.CharField(choices=[('FANT', 'Fantasy'), ('CRIM', 'Crime & Thriller'), ('FICT', 'Fiction'), ('SCFI', 'Science Fiction'), ('HORR', 'Horror'), ('ROMA', 'Romance'), ('TEEN', 'Teen & Young Adult'), ('KIDS', "Children's Books"), ('ANIM', 'Anime & Manga'), ('OTHR', 'Others')], default='OTHR', max_length=4),
        ),
        migrations.AddField(
            model_name='book',
            name='secondary_genre',
            field=models.CharField(blank=True, choices=[('FANT', 'Fantasy'), ('CRIM', 'Crime & Thriller'), ('FICT', 'Fiction'), ('SCFI', 'Science Fiction'), ('HORR', 'Horror'), ('ROMA', 'Romance'), ('TEEN', 'Teen & Young Adult'), ('KIDS', "Children's Books"), ('ANIM', 'Anime & Manga'), ('OTHR', 'Others')], max_length=4, null=True),
        ),
    ]
